{% set image_name = image_name or "cirros" %}
---
  ScenarioPlugin.cinder_storage_four:
    - args:
        flavor:
          name: gig

        image:
          name: "{{image_name}}"
        size: 1
        network_create_args: { }
        subport_count: 2
        boot_server_kwargs: {}
        auto_assign_nic: True
        nics:
          - net-id: "{{network_id}}"
      runner:
        type: "constant"
        times: {{cinder_nova_times}}
        concurrency: {{cinder_nova_concurrency}}
      context:
        users:
          tenants: 1
          users_per_tenant: 2
          user_choice_method: "round_robin"
        flavors:
          - name: gig
            ram: 6024
            disk: 4
            vcpus: 4
        quotas:
          nova:
            instances: -1
            cores: -1
            ram: -1
          cinder:
            gigabytes: -1
            volumes: -1
      sla:
        failure_rate:
          max: 0

  ScenarioPlugin.Ephemeral_Storage:
    -
      args:
        flavor:
            name: gig
        image:
            name: "{{image_name}}"
        auto_assign_nic: True
        nics:
          - net-id: "{{network_id}}"
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        flavors:
          - name: gig
            ram: 6024
            disk: 10
            vcpus: 4
            ephemeral: 10
        quotas:
          nova:
            instances: -1
            cores: -1
            ram: -1
          cinder:
            gigabytes: -1
            volumes: -1
      runner:
        concurrency: {{ephemeral_concurrency}}
        times: {{ephemeral_times}}
        type: "constant"
      sla:
        failure_rate:
          max: 0

  KeystoneBasic.authenticate_user_and_validate_token:
    -
      args: {}
      runner:
        type: "constant"
        times: 2000
        concurrency: 20
      sla:
        failure_rate:
          max: 0

